stages:
  - build
  - test

jobs:
  - name: viewworkspace
    stage: test
    image: alpine
    script:
      - echo helo
    workspace:
      - persist:
          root: sdasd
          paths:
            - foor
      - attach: helo 

  - name: viewlog
    stage: test
    image: sunasteriskrnd/php-workspace:7.4
    script:
    - cat log.txt
    release:
      environment: Production
      url: https://example.com
