workspace: true

stages:
  - build
  - test

jobs:
- name: build
  stage: build
  image: sunasteriskrnd/php-workspace:7.4
  cache:
  - key: comopser_vendor_$CI_BRANCH
    paths:
      - vendor
  - composer install
  script:
  - composer install
  after_script:
  - echo "Finish job"
 
