workspace: true

stages:
- Build
- Test

jobs:
- name: Run tests
  stage: Build
  image: alpine
  services:
  - redis:alpine
  script:
  - echo Hello

- name: Sleep
  stage: Build
  image: alpine
  script:
  - sleep 10

- name: Wake up
  stage: Build
  image: alpine
  script:
  - echo Hello

- name: Sleep again
  stage: Build
  image: alpine
  script:
  - sleep 10

- name: Sleep more
  stage: Test
  image: alpine
  script:
  - sleep 10

- name: Say bye!
  stage: Test
  image: alpine
  script:
  - sleep 10
  - echo Bye
